import { json } from "@sveltejs/kit";
import type { RequestHandler } from "./$types";

export const GET: RequestHandler = async () => {
  // Mock data - will be replaced with real DB queries
  const streaks = [
    {
      id: "journaling",
      name: "Journaling",
      icon: "📝",
      description: "Daily entry - system requires data",
      frequency: "Daily",
      current_streak: 44,
      best_streak: 44,
      completed_today: true,
    },
    {
      id: "three_daily_happiness",
      name: "3 Good Things",
      icon: "🙏",
      description: "Gratitude - 3 things that went well + why",
      frequency: "Daily",
      current_streak: 44,
      best_streak: 44,
      completed_today: true,
    },
    {
      id: "vampire_shot",
      name: "Vampire Shot",
      icon: "🧄",
      description: "Garlic-Lemon-Turmeric shot (-22% cancer risk)",
      frequency: "Daily",
      current_streak: 15,
      best_streak: 30,
      completed_today: true,
    },
    {
      id: "morning_electrolytes",
      name: "Electrolytes",
      icon: "💧",
      description: "Morning hydration BEFORE coffee",
      frequency: "Daily",
      current_streak: 20,
      best_streak: 25,
      completed_today: true,
    },
    {
      id: "supplements",
      name: "Supplements",
      icon: "💊",
      description: "Longevity stack (D3, Omega-3, B-Complex, Creatine, etc.)",
      frequency: "Daily",
      current_streak: 25,
      best_streak: 35,
      completed_today: true,
    },
    {
      id: "sleep_tracking",
      name: "8h Sleep",
      icon: "😴",
      description: "Target: 22:00-06:00 (8h)",
      frequency: "Daily",
      current_streak: 12,
      best_streak: 20,
      completed_today: false,
    },
    {
      id: "plan_tomorrow",
      name: "Plan Tomorrow",
      icon: "📋",
      description: "Evening planning (21:00-21:30) - reduce morning fatigue",
      frequency: "Daily",
      current_streak: 8,
      best_streak: 15,
      completed_today: false,
    },
    {
      id: "running",
      name: "Running",
      icon: "🏃",
      description: "Cardio, mental clarity, longevity",
      frequency: "3-5x/week",
      current_streak: 3,
      best_streak: 15,
      completed_today: false,
    },
    {
      id: "sales_learning",
      name: "Sales Learning",
      icon: "📚",
      description: "Micro-learning curriculum (3-5 min/day)",
      frequency: "Mon-Fri",
      current_streak: 7,
      best_streak: 30,
      completed_today: true,
    },
    {
      id: "sauna",
      name: "Sauna",
      icon: "🧖",
      description: "Detox, cardiovascular health, stress relief",
      frequency: "Weekly",
      current_streak: 2,
      best_streak: 10,
      completed_today: false,
    },
  ];

  return json({ streaks });
};
